### ISSUE TITLE
Launch games with wine?

### ISSUE THREAD

**Issue by crbble** [dotfloat/steam-appmanifest#13]
Can you launch the downloaded files with wine or is it missing some windows Steam stuff?
Thanks.

**Comment by dotfloat** [comment]
It depends on the game.

Some games require Steam to be running to verify that you've bought the game. Unfortunately, they can't interface with native Linux Steam.

Here's a list of DRM-free Steam games that should theoretically work without wine Steam: [Link](http://steam.wikia.com/wiki/List_of_DRM-free_games)
