### ISSUE TITLE
[question] Will games work with steam client? 

### ISSUE THREAD

**Issue by sushantdhiman** [dotfloat/steam-appmanifest#14]
Games downloaded by this method will run on windows platform , but will I be able to run them with Steam Client so I can still track the Achievement etc

**Comment by dotfloat** [comment]
Nope. Games can't interface with the Steam for Linux, so you'd need to be running Steam through Wine. This, of course, defeats the purpose of the script.

**Comment by sushantdhiman** [comment]
Thanks, This mean it would work with windows Steam client.
