### ISSUE TITLE
Update downloadlink and add a list of non-working games?

### ISSUE THREAD

**Issue by LeonardKoenig** [dotfloat/steam-appmanifest#9]
GTA Vice City ain't working for me atleast, Brutal Legend however does (and so does GTA:SA, lol)

Link doesn't work, but this one does:
https://raw.githubusercontent.com/dotfloat/steam-appmanifest/master/steam-appmanifest.py

**Comment by dotfloat** [comment]
Alright, sorry for answering this a whopping 18 days later. I fixed the link, thank you!

As for having a list of non-working games, I don't have the resources to test every game and retest for every new update to see if it's possible to download. It's a good idea, but it's just not feasable.

**Comment by LeonardKoenig** [comment]
No problem ;-)

I think we could have just a list in the repo and everybody who can confirm working/non-working just opens an issue or a pull request. I'ld recommend also giving AppID and date tested.
